### PR TITLE
Add github actions workflow

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Adds a r cmd check github actions workflow. Also made some changes to the test script in order to make it more general.

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
@chantelwetzel-noaa , feel free to merge this in whenever you are ready! Note the test may "fail", but I think it might highlight a real issue that needs to be address? Maybe we can go over the workflow file and log together, when you have time.

**Comment by k-doering-NOAA** [comment]
Also, @chantelwetzel-noaa , I found some info about github actions notifications: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

It sounds like what we can do is have you update the `schedule:` build trigger, (maybe just put in a different time to run it), and the notifications should come your way!

**Comment by chantelwetzel-noaa** [comment]
@k-doering-NOAA  Will do.  I pushed a minor edit at the end of the day yesterday to see what would happen. I was super happy to have a failed check email this morning.

**Comment by k-doering-NOAA** [comment]
> @k-doering-NOAA Will do. I pushed a minor edit at the end of the day yesterday to see what would happen. I was super happy to have a failed check email this morning.

Haha, maybe the only time you will be happy about a failed check email 😆 

Let me know if you want to go through the log together! Happy to help you "decode" it :)

**Pull request merged**
